services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\CrowdfundingBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Message}'
